config/routes.rb
TeknofireNet::Application.routes.draw do

  resources :notes
  
  namespace :admin do
    resources :notes
  end
  

  match '/signin' => 'sessions#new', :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'

  root :to => 'welcome#index'

end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  belongs_to :user
  
  attr_accessible :provider, :uid, :user_id, :user
  
  validates_presence_of :user_id, :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider
  
  def self.find_from_hash(hash)
    find_by_provider_and_uid(hash['provider'], hash['uid'])
  end

  def self.create_from_hash(hash, user = nil)
    user ||= User.create_from_hash!(hash)
    Authorization.create(:user => user, :uid => hash['uid'], :provider => hash['provider'])
  end
end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :content, :title
  
  validates_presence_of :content, :title
  
  
  def to_s
    self.title
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authorizations
  
  has_many :transactions
  has_many :coffee_charges
  
  attr_accessible :name, :email
  
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.create_from_hash!(hash)
    create(:name => hash['info']['name'], :email => hash['info']['email'])
  end
  
  def balance
    transactions.sum(:amount)
  end
  
  def cups
    (self.balance / 0.5).to_i
  end
end

app/controllers/admin/notes_controller.rb
class Admin::NotesController < AdminController
  def index
    @notes = Note.order('updated_at DESC')
  end
  
  def new
    @note = Note.new
  end
  
  def create
    @note = Note.new(params[:note])
    
    respond_to do |format|
      if @note.save
        format.html {
          flash[:success] = "Saved note #{@note}"
          redirect_to admin_notes_path
        }
      else
        format.html {
          render :new
        }
      end
    end
  end
  
  def edit
    @note = Note.find(params[:id])
  end
  
  def update
    @note = Note.find(params[:id])
    
    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html {
          flash[:success] = "Saved note #{@note}"
          redirect_to admin_notes_path
        }
      else
        format.html {
          render :edit
        }
      end
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :require_admin_auth
  before_filter :hide_header
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  protected
  
  def hide_header
    @hide_header = true
  end
  
  def hide_header?
    @hide_header
  end
  helper_method :hide_header?
  
  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def signed_in?
    !!current_user
  end

  helper_method :current_user, :signed_in?

  def current_user=(user)
    @current_user = user
    session[:user_id] = user.id
  end
  
  def redirect_back_or_default(url)
    if session[:redirect_back_location].present?
      l = session.delete(:redirect_back_location)
      redirect_to l
    else
      redirect_to url
    end
  end
  
  def require_login
    if current_user.nil?
      session[:redirect_back_location] = request.url
      redirect_to signin_path
    end
  end
  
  def require_admin_auth
    if current_user.nil?
      session[:redirect_back_location] = request.url
      redirect_to signin_path
    elsif not current_user.admin?
      flash[:error] = 'You do not have permission to access this page'
      redirect_to root_url
    end
  end  
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    # @notes = %w{ mobile_mapping_w_enyojs geojson_is_wrong postgis_frenzy 
      # mongodb_geospatial high_performance_data_vis openlayers3 }
    @notes = Note.order('updated_at DESC')
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => :create
  
  def create
    unless @auth = Authorization.find_from_hash(auth_hash)
      @auth = Authorization.create_from_hash(auth_hash, current_user)
    end
    
    self.current_user = @auth.user
    
    flash[:success] = "Successfully logged in as #{current_user.name}"
    redirect_back_or_default(root_url)
  end
  
  def destroy
    reset_session
    flash[:success] = 'Signed out!'
    redirect_back_or_default(root_url)
  end
  
  def new
    redirect_to('/auth/google')
  end
  
  def failure
    flash[:error] = "Authentication error: #{params[:message].humanize}"
    redirect_to root_url
  end
  
  protected
  
  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/admin/notes_helper.rb
module Admin::NotesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_messages
    output = ""
    flash.each do |type,msg|
      if msg.is_a? Array
        msg.each do |m|
          output << message(type, m)
        end
      else
        output << message(type, msg)
      end
    end
    output.html_safe
  end
  
  def message(type, text)
    content_tag(:div, class: "alert alert-#{type}") do
      "#{text} #{link_to 'x', '#', class: 'close', "data-dismiss" => "alert"}".html_safe
    end
  end
  
  def avatar_url(email, size=48)
    email = '' if email.nil?
    gravatar_id = Digest::MD5.hexdigest(email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/notes/_form.html.haml
= form_for [:admin, @note] do |f|
  - if @note.errors.count > 0
    .alert.alert-error
      %h3 Error while trying to save the note
      %ul
        - @note.errors.full_messages.each do |msg|
          %li= msg
  .control-group
    = f.label :title, class: 'control-label'
    .controls
      = f.text_field :title, class: 'span12'
  .control-group
    = f.label :content, class: 'control-label'
    .controls.ace{ data: { editor: 'ace', mode: 'markdown' } }
      .navbar.navbar-static-top
        .navbar-inner
          .btn-group
            %button.btn.btn-small{ type: 'button', title: 'Undo', data: { action: 'undo' } }
              = fa_icon "undo"
            %button.btn.btn-small{ type: 'button', title: 'Redo', data: { action: 'redo' } }
              = fa_icon "repeat"
    
      = f.text_area :content, class: 'span12', rows: 15
      
  .form-actions
    = link_to admin_notes_path, class: 'btn' do
      = fa_icon "arrow-left"
      Cancel
    .pull-right
      = f.submit class: 'btn btn-primary'

app/views/admin/notes/edit.html.haml
%h2= "Edit Note: #{@note}"
= render 'form'

app/views/admin/notes/index.html.haml
%table.table.table-bordered.table-stripped
  %thead
    %tr
      %td{colspan:3, style: 'padding:0px;'}
        .navbar.navbar-static-top
          .navbar-inner
            .brand Admin::Notes
            .pull-right
              = link_to new_admin_note_path, class: 'btn btn-success' do
                = fa_icon "plus"
                New Note
    %tr
      %th Title
      %th Last Updated
      %th Actions
  %tbody
    - @notes.each do |note|
      %tr
        %td= note.title
        %td= note.updated_at
        %td
          = link_to edit_admin_note_path(note), class: 'btn btn-primary' do
            = fa_icon "edit"

app/views/admin/notes/new.html.haml
%h2 New Note
= render 'form'

app/views/layouts/_analytics.html.erb
<script type="text/javascript">
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-41369546-1', 'teknofire.net');
  ga('send', 'pageview');
</script>

app/views/layouts/_footer.html.haml
.row-fluid
  .span12{style: "text-align: center;"}
    %ul.nav.nav-pills.social
      %li
        = mail_to 'will@teknofire.net', '<i class="icon-envelope"></i>'.html_safe
      %li
        = link_to 'http://twitter.com/teknofire', target: :_blank do
          = fa_icon "twitter"
      / %li
      /   = link_to '#', target: :_blank do
      /     = fa_icon "facebook"
      %li
        = link_to 'http://github.com/teknofire', target: :_blank do
          = fa_icon "github"
.row-fluid
  .span6
    %section#links
      %h3 Links
      %address
        %b Work:
        = link_to 'Geographic Information Network of Alaska', 'http://www.gina.alaska.edu'
  .span6

= render 'layouts/analytics'

app/views/layouts/_header.html.haml
.title
  = render 'layouts/title'

.menu
  %ul.nav.nav-pills.pull-left
    %li
      = link_to '/#home', data: { scroll: '#home' } do
        = fa_icon 'home'
        Home 
    %li
      = link_to '/#blog', data: { scroll: '#blog' } do
        = fa_icon 'microphone'
        Blog
    = render 'layouts/page_nav'
  %ul#small-title.pull-right.nav.nav-pills{ style: 'display: none;' }
    %li
      = link_to root_url do
        = fa_icon 'fire'
        teknofire.net

app/views/layouts/_page_nav.html.haml
%li
  = link_to notes_path do
    = fa_icon 'edit'
    Notes
%li
  = link_to 'http://github.com/teknofire' do
    = fa_icon 'github'
    Code
- if signed_in?
  %li
    = link_to signout_path do
      = fa_icon 'signout'
      Signout
- else
  %li
    = link_to signin_path do
      = fa_icon 'signin'
      Signin

app/views/layouts/_title.html.haml
= fa_icon "fire"
teknofire.net
.byline Ruby, Rails and HTML5

app/views/layouts/_welcome_header.html.haml
.title
  = render 'layouts/title'

.menu
  %ul.nav.nav-pills.pull-left
    %li
      = link_to '/#home' do
        = fa_icon 'home'
        Home 
    %li
      = link_to '/#blog' do
        = fa_icon 'microphone'
        Blog
    = render 'layouts/page_nav'
    
  %ul.nav.nav-pills.pull-right
    %li
      = link_to root_url do
        = fa_icon "fire"
        teknofire.net

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %title TeknofireNet
    = stylesheet_link_tag    "admin", :media => "all"
    = javascript_include_tag "admin", "/ace/ace.js"
    = csrf_meta_tags
  %body.hide_header
    #home
    .header
      .container
        = render 'layouts/header'
    .page-alert
      = flash_messages        
    .no-splash
    .container
      = yield
    .footer
      .container
        = render 'layouts/footer'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title TeknofireNet
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body.hide_header
    .header
      .container
        = render 'layouts/header'
    .page-alert
      = flash_messages        
    .no-splash
    .container
      = yield
    .footer
      .container
        = render 'layouts/footer'
:javascript
  $(document).ready(function() {
  });

app/views/layouts/welcome.html.haml
!!!
%html
  %head
    %title TeknofireNet
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    #home
    .header
      .container
        = render 'layouts/header'
    .page-alert
      = flash_messages
    .splash
      .container
        = yield :splash
    .container
      = yield
    .footer
      .container
        = render 'layouts/footer'
:javascript
  $(document).ready(function() {
    $(document).on('click', '[data-scroll]', function(evt) {
      var target = $(evt.currentTarget).data('scroll');
      if(!$(target)) { return; }
      
      evt.preventDefault();
      
      var parent = $('html,body');
      var cur_scroll = parent.scrollTop();
      parent.animate({
        scrollTop: $(target).offset().top
      });
    })
  });

app/views/notes/_geojson_is_wrong.html.haml
%h3 
  GeoJSON is Spectacularly Wrong
  %span.small :: 5/23/2013
:markdown
  The little format that could
  
  * It is what it is, no plans for a 2.0 version
  * There are aother options like TopoJSON

app/views/notes/_high_performance_data_vis.html.haml
%h3 
  High Performance Data Viz
  %span.small :: 5/22/2013
:markdown
  * search
    * load data once and search lots of times
    * search index
      * grid - ok/meh
      * tree data structures - better
      * crossfilter - interesting indexing system
  * geometric clipping
  * polyline simplification
    * mourner.github.com/simplify-js
  * reduce dom objects
    * clustering
      * hierarchical clustering - good for doing it once and having multiple levels
  * data loading and processing
    * web workers - multi-threaded calculations in javascript
    * loading data in the worker
    * transferable objects
      var array = new Float16Array(len);
      var buffer = array.buffer
      postMessage()
    * asm.js
  * rendering backends
    * SVG, Canvas, WebGL
  

app/views/notes/_mobile_mapping_w_enyojs.html.haml
%h3 
  Mobile Mapping w/ EnyoJS
  %span.small :: 5/23/2013
:markdown
  * IE8 or better
  * MVC js framework (think ExtJS)
  * Integrates with Maven build system and some test frameworks
  * Not for us
  * Mobile app development handled by phonegap

app/views/notes/_mongodb_geospatial.html.haml
%h3 
  MongoDB Geospatial
  %span.small :: 5/22/2013
:markdown
  * Adding OGC simple features
  * Using Google S2 sphere library

app/views/notes/_note.html.haml
%section{ id: dom_id(note) }
  %h3 
    = note.title
    %span.small
      = ":: #{note.updated_at.strftime('%Y.%m.%d')}"
  :markdown
    #{note.content}

app/views/notes/_openlayers3.html.haml
%h3 
  Openlayers3
  %span.small :: 5/22/2013
:markdown
  * 2D and 3D performance
    * Canvas and WebGL
  * Projections are 1st class object
  * om.Map and om.View
  * om.layer and om.source
    * seperate the layer config from the source config
    * setup the same layer but pull from different sources
    * sources can be async configured
    * can be setup to configure the tile/wms source on the fly by pulling capabilities
    * tile queue is based on the cursor
  * om.interaction
    * drag, rotate, keyboardpan, touchzoom, etc...
  * om.control
    * zoom, buttons, scaleline, attribution, etc...
  * ol.Overlay
    * Method to have things anchored to the map
    * can be used with bootstrap popover
  * ol.animation
    * panning and kinetic movement
    * strong animation framework
    * spin the map
    * bounce
    * fly
  * Vectors and 2D rendering
    * indexing by deometry type and bounds (R-Tree)
    * render by tiles
    * interacting with features
      * same api for all layer types
    * 20000 features was just about instant
    * Vector Format Parsers
      * GeoJSON, asycn loading api
  * Closure Compiler
    * Tomorrows talk about OL3 will cover this
  

app/views/notes/_pgc_visit.html.haml
* checksums for all files
* geeeee-dal
* 

app/views/notes/_postgis_frenzy.html.haml
%h3 
  PostGIS Frenzy
  %span.small :: 5/23/2013
:markdown
  * Read and Write GeoJSON, KML, plus all the other good stuff
  * linear referencing
    * Good for stuff like DOT and Fish people where they say things are located at mile 10 of a highway or at a particular distance down a river
    * ST_LocateAlong, ST_LocateBetween, ST_AddMeasure
  * Curves
    * ST_LineToCurve!!!
  * Reprojections
    * ST_Transform
  * Geography
    * Good to dealing with modeling data on a sphere
    * Only has a small number of functions (15 native)
      * Intersects, Distance, DWithin, Area 
    * Cast to another geometry to get the others
    * Indexes spherical data
    * new gui loader for shapefiles
  * 3d types
    * support volumes
    * triangle, tin, polyhedrals
    * AsX3D, AsGML, AsText, AsBinary
    * now support 3d and 4d indexing (2.0)
  * Added support for rasters
    * Evelope, ConvexHull, Polygon
  * Topology (2.0)
    * Good for simplifying things that have shared edges
  * Indexed KNN (nearest neighbor) (2.0)
    * ORDER BY geom <-> (SELECT geom FROM ...) LIMIT 10
  * Validity Reporting
    * ESRI vs OGC method of handling polygons
    * IsValidReason, IsValid
    * ST_MakeValid() (2.0)
  * Perfomance improvements (2.1)
    * Raster ST_Union(), navtive implementation (2.1)
    * 10x faster ish
    * Geography ST_Distance and ST_DWithin ~ 30x faster
    * New R-Tree spitter
    * ND Indexes

app/views/notes/index.html.haml
= render @notes

app/views/welcome/index.html.haml
- content_for :splash do
  .row
    .col-lg-6
      #home.well
        %h3 RubyConf is now over
        %p So RubyConf just ended and it was a huge blast, it was nice to meet a bunch of new folks and see all the neat things people are doing with Ruby. 
        
        %p Some of the highlights for the conference included the #RubyOnSails event and the "My KidsRuby Journey" by PJ and Katie Hagerty and "That's Not Very Ruby of You" by Ernie Miller keynote talks.  I really enjoyed listening to the talks about using partial evaluators to build compilers and machine learning tools.
        
        %p Piles of new things to check out once I get back home like Grape, ServerSpec (for chef), queue_classic.  
    .col-lg-6
      .well
        %h3 
          = fa_icon "wrench"
          What I do
        %p 
          I work for the 
          = link_to 'http://www.gina.alaska.edu', target: :_blank do
            Geographic Information Network of Alaska
            = fa_icon "external-link"
          doing development and project management.
        %p 
          My primary work involves working with GIS data and doing web development using Ruby on Rails and various JavaScript technologies.
        
%section#blog
  %h1 Stay tuned while we adjust the antenna